INSTALL_ANYDESK_COMMAND = "Install AnyDesk"
GET_CODE_COMMAND = "Get Code"
POWER_ON_ANYDESK = "Power On AnyDesk"
POWER_OFF_ANYDESK = "Power Off AnyDeks"

INSTALL_ANYDESK_COMMAND_CODE = 0
GET_CODE_COMMAND_CODE = 1
POWER_ON_ANYDESK_CODE = 2
POWER_OFF_ANYDESK_CODE = 3

IP = "127.0.0.1"
PORT = 44444

ANYDESK_FILE_PATH = "C:\\Users\\Matan\\Documents\\CProjects\\AnyDeskVirus\\anyDeskFile\\AnyDesk.exe"

ANYDESK_CODE_ERROR = "no-code__"